import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Profile from "./components/profile";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Wassup-Chicken",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <main className="max-w-3xl justify-center items-center mx-auto px-4 py-8">
          <Profile />
          {children}
        </main>
      </body>
    </html>
  );
}
